### ISSUE TITLE
Follow / Unfollow feature

### ISSUE THREAD

**Issue by aseerkt** [aseerkt/apollo-instagram-clone#8]
**Tasks need to completed**
- [ ] Create `Follower` entity
- [ ] Create `toggleFollow` mutation.
- [ ] Create `getFollowSuggestions` query.
- [ ] Display follow suggestions in frontend
- [ ] Profile page should include Follow/Unfollow options

**Comment by aseerkt** [comment]
backend files are not committed to this branch
